env:
  max_steps: 500
  grasp_radius: 0.10
  action_scale: 0.03
  inner_xyh: [0.26, 0.26, 0.16]
  wall_thickness: 0.012
  auto_grasp: true
  auto_release: true
  release_xy_margin: 0.10
  release_z_thresh: 0.12
  lift_height: 0.14
  over_bin_height: 0.18
